export {
  parseTemplate,
  parseTemplateToFilename,
  validateTemplate,
  validateTemplatePattern,
  extractVariables,
  getTemplateVariables,
  sanitizeFilename,
  previewTemplate,
  hasCounterVariable,
  countVariableOccurrences,
  SUPPORTED_VARIABLES,
  type TemplateVariable,
  type TemplateValidationResult,
} from "./templateParser";

export {
  getTemplatesSettings,
  isTemplatesPluginEnabled,
  processTemplateContent,
  parseTitleTemplate,
  parseTitleTemplateToFilename,
  sanitizeForFilename,
  DEFAULT_DATE_FORMAT,
  DEFAULT_TIME_FORMAT,
  DEFAULT_FILENAME_TIME_FORMAT,
  type TemplatesSettings,
} from "./templatesIntegration";

export {
  extractPrompts,
  hasPrompts,
  countPrompts,
  substitutePrompts,
  previewWithPrompts,
  validatePromptValue,
  validateAllPromptValues,
  allPromptsValid,
  sanitizePromptValue,
  validatePromptName,
  createPromptSyntax,
  syncPromptsWithPattern,
  generatePromptId,
  type PromptValidationResult,
} from "./promptParser";
